version: '3.8'

services:
  shared:
    build:
      context: .
      dockerfile: Dockerfile
      target: shared
    volumes:
      - ./packages/shared:/app/packages/shared
      - shared_dist:/app/packages/shared/dist

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - shared_dist:/app/packages/shared/dist
    depends_on:
      - shared
    environment:
      - PORT=4000
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - shared_dist:/app/packages/shared/dist
    depends_on:
      - shared
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:4000

volumes:
  shared_dist: 