version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  shared:
    build:
      context: .
      dockerfile: Dockerfile
      target: shared
    volumes:
      - ./packages/shared:/app/packages/shared
      - shared_dist:/app/packages/shared/dist

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - shared_dist:/app/packages/shared/dist
    depends_on:
      - shared
      - mongodb
      - redis
    environment:
      - PORT=4000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/unoking
      - REDIS_URI=redis://redis:6379

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - shared_dist:/app/packages/shared/dist
    depends_on:
      - shared
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:4000

volumes:
  shared_dist:
  mongodb_data:
  redis_data: 