name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME_FRONTEND: uno-king-frontend
  AZURE_WEBAPP_NAME_BACKEND: uno-king-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: |
          cd packages/shared
          npm run build

      - name: Build frontend
        run: |
          cd packages/frontend
          npm run build
        env:
          VITE_BACKEND_URL: https://${{ env.AZURE_WEBAPP_NAME_BACKEND }}.azurewebsites.net

      - name: Build backend
        run: |
          cd packages/backend
          npm run build

      - name: Deploy frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: packages/frontend/dist

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: packages/backend/dist 